title: TM129 Robotics Practical Activities
auther: us, innit
only_build_toc_files        : true
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "**.md"]
execute:
  execute_notebooks         : off
