module:
  code: TM129-Robotics
  presentation: 21J
type: jupyter-notebook
base: "3.7"
packages:
  apt:
    - build-essential
  pip:
    - nbev3devsim>=0.0.9
    - ou-tm129-py>=0.0.8
content:
  - source: content
    target: content
    overwrite: never
scripts:
  build:
    - commands: |
        pip3 install --index-url https://google-coral.github.io/py-repo/ tflite_runtime
