FROM ousefuldemos/tm129-robotics2020:latest

ENV JUPYTER_TOKEN letmein


#The ousefuldemos/tm129-robotics2020:latest is built from the repo
# https://github.com/innovationOUtside/tm129-robotics2020/
# by a Github Action watching releases
 
#Then run:

# docker pull ousefuldemos/tm129-robotics2020:latest
# docker build --tag ousefulcoursecontainers/ou-tm129:current .
# docker push ousefulcoursecontainers/ou-tm129:current
 