name: Deployment

on:
  push:
    branches: [ default ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Base Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-venv
        pip3 install poetry git+https://github.com/mmh352/ou-container-builder.git

    - name: Generate the Dockerfile
      run: |
        ou-container-builder --no-build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: mmh352/tm129-robotics-21j
        flavor: |
          latest=true
        tags: |
          type=sha

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: mmh352
        password: ${{ secrets.DOCKERACCESSTOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        pull: true
        push: true
        tags: ${{ steps.meta.outputs.tags }}
