name: Jupyter Book Publish
# ish via https://github.com/atrisovic/weather-panel.github.io/blob/master/.github/workflows/pythonpackage.yml#L10
# Relies on the presence of a jupyterbook branch, as set up in the setup.yml workflow
on:
  push:
    branches:
    - master

# The intended workflow is:
# - spot a checkin to master
# - use that content to generate a book build in jupyterbook branch
# - copy the built site to gh-pages branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: setup jupyterbook branch
      uses: peterjgrainger/action-create-branch@v2.0.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: jupyterbook
    - uses: actions/checkout@v2
    - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install python3-pip
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Jupyter Book 
      run: |
        pip install jupyter-book
        (test binder/requirements.txt && pip install binder/requirements.txt) || echo "No additional pip requirements."
    - name: Set up and build Jupyter book
      run: |
        sudo chown -R $(whoami):$(whoami) .
        
        ( test -f toc.yml && echo "TOC exists") || jupyter-book toc . --path-output toc.yml 
        
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git checkout -b jupyterbook
        git merge master --allow-unrelated-histories
        (test -d buildbook && echo "Book dir (buildbook) already created") || jupyter-book create buildbook --content-folder ./materials --config _config.yml --toc toc.yml --overwrite 
        #Perhaps provide a config setting to allow execution or not?
        jupyter-book build --execute --overwrite buildbook
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install bundler
      run: |
        sudo gem install bundler -v 1.17.2
        bundle config path vendor/bundle
    - name: Install Jekyll and build book
      run: |
        cd buildbook 
        bundle install 
        bundle exec jekyll build
    - name: Push build branch	jupyterbook
      run: |       
        git add --all --force buildbook
        git commit -a --allow-empty-message -m 'Push build branch'
 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: jupyterbook
        force: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./buildbook/_site # If a page is deleted, is it removed from _site?
