#https://github.com/machine-learning-apps/repo2docker-action

#For adding secrets:
# - from main page of repo, click  Settings
# - from left sidebar, click Secrets
# - enter secret name and value

name: Build Notebook Container
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Push to dockerhub'  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - name: checkout files in repo
      uses: actions/checkout@master

    - name: clean build repo of production cruft
      run: |
        mv content/README_FIRST.ipynb ./README_FIRST.ipynb
        rm README.md && rm -rf content/00* && rm -rf outreach && rm -rf production && rm -rf release
        rm -rf .VM && rm -rf .images && rm -rf && rm -rf .md
        
        
    - name: try-local-build
      #uses: ouseful-PR/repo2docker-action@master #forked and tweaked
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "ousefuldemos/tm129-robotics2020"
